version: "3.2"

services:
  havenly_db:
    container_name: havenly_db
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: havenly
    expose:
      - "3306"
    ports:
      - "33062:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  havenly_node:
    build: .
    container_name: havenly_node
    environment:
      DB_HOST: havenly_db
      DB_NAME: havenly
      DB_PASSWORD: root
      DB_USER: root
    depends_on:
      - havenly_db
    volumes:
      - "${PWD}/client:/app/client:delegated"
      - "${PWD}/public:/app/public:delegated"
      - "${PWD}/server:/app/server:delegated"
      - "${PWD}/package.json:/app/package.json:delegated"
    entrypoint:
      - /app/entrypoint.sh
    ports:
      - "9001:9001"
      - "36625:36625" # hot loader websocket
